name: Action test on MacOS

on:
  # schedule:
  #   - cron: "0 4 * * MON-FRI" # Runs at 02:00 UTC
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: macos-latest
    steps:
      - id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@main
        with:
          branch: main

      - run: echo ${{ steps.check-branch-exists.outputs.exists }}

      - if: steps.check-branch-exists.outputs.exists == 'true'
        run: echo 'main branch exists'

      - if: steps.check-branch-exists.outputs.exists == 'false'
        run: echo 'main branch NOT FOUND'