name: Action test on Ubuntu

on:
  # schedule:
  #   - cron: "0 2 * * MON-FRI" # Runs at 02:00 UTC
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@main
        with:
          branch: main

      - if: ${{ steps.check-branch-exists.outputs.exists }} == 'true'
        run: echo 'main Branch exists'

      - if: ${{ steps.check-branch-exists.outputs.exists }} == 'false'
        run: echo 'main Branch DOESN'T exist'