name: Action test on Windows

on:
  # schedule:
  #   - cron: "0 6 * * MON-FRI" # Runs at 02:00 UTC
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: windows-latest
    steps:
      - id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@main
        with:
          branch: main

      - if: ${{ steps.check-branch-exists.outputs.exists }} == 'true'
        run: echo 'main branch exists'

      - if: ${{ steps.check-branch-exists.outputs.exists }} == 'false'
        run: echo 'main branch NOT FOUND'